# Generated by Django 5.2.6 on 2025-09-10 06:29

import loans.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[loans.models.validate_amount])),
                ('tenure', models.PositiveIntegerField(help_text='Tenure in months', validators=[loans.models.validate_tenure])),
                ('interest_rate', models.FloatField(help_text='Yearly interest %', validators=[loans.models.validate_interest])),
                ('monthly_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_interest', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),
    ]
