# Generated by Django 5.2.6 on 2025-09-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('FORECLOSED', 'Foreclosed'), ('REJECTED', 'Rejected'), ('REPAID', 'Repaid'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=10),
        ),
    ]
