# Generated by Django 5.2.1 on 2025-10-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_alter_loan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='foreclosure_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid to foreclose the loan', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='foreclosure_date',
            field=models.DateTimeField(blank=True, help_text='Date when loan was foreclosed', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amortization_schedule',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.FloatField(default=10.0, help_text='Fixed 10% yearly interest'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_installment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_payable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
