# Generated by Django 5.2.1 on 2025-10-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_loan_foreclosure_amount_loan_foreclosure_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('EMI', 'Regular EMI Payment'), ('FORECLOSURE', 'Foreclosure Settlement')], default='EMI', help_text='Type of payment', max_length=15),
        ),
    ]
